### ISSUE TITLE
Labels have stopped showing the text

### ISSUE THREAD

**Issue by ghost** [fredericseiler/trelabels#16] opened 2019-03-14 12:05 UTC
The extension just stopped working the other day.  The label text no longer shows on the cards.  The menu no longer lists the different display options.

**Comment by fredericseiler** [comment] 2019-03-17 18:31
What other Trello extension(s) are you using ?

![image](https://user-images.githubusercontent.com/954168/54496068-18acc100-48eb-11e9-824d-505027a2cfc1.png)

**Comment by byalpel** [comment] 2019-03-24 23:39
Hi,
I have the same problems. And when I click on the button to display the labels, nothing happens.
I'm using the "Original Card Counter for Trello" extension, but it always worked like a charm until now..

Any incompatibility with Chrome (Version 72.0.3626.121 (Official Build) (64-bit))?

**Comment by ghost** [comment] 2019-03-25 14:38
I'm not using any other trello extensions or powerups.


Best Regards,

Brad

________________________________

**Comment by fredericseiler** [comment] 2019-03-29 09:56
Yep, it's not working anymore for me either. I'll check what's wrong this week-end.

**Comment by fredericseiler** [comment] 2019-04-15 12:15
I can't reproduce the issue anymore, it's always working for me now...

**Comment by Deutschi** [comment] 2019-05-07 09:15
The class names were changed by Trello, so the startup didn't work for me any longer (and other people it seems). I created a pull request to fix that. Please try it out @fredericseiler . Hopefully this works for everyone.

**Comment by fredericseiler** [comment] 2019-05-09 08:48
I'm wondering if the Trello team rolls a new version of the app only for a specific panel, because I don't encounter that issue and the same goes for a friend of mine.

**Comment by fredericseiler** [comment] 2019-05-09 08:55
Can you all give me infos about your OS and browser (name & version) ?

**Comment by Deutschi** [comment] 2019-05-09 09:06
Win 10 Pro x64 1809 (OS Build 17763.437)
Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by fredericseiler** [comment] 2019-05-09 09:17
Same OS, same browser... So, my best guess is a staged update rollout by Trello.

**Comment by Deutschi** [comment] 2019-05-09 09:26
In my Firefox I am not able to reproduce this, I always get the "old" style you have. I guess you are right with your assumption.

**Comment by fredericseiler** [comment] 2019-05-09 14:35
Fixed with [the help](https://github.com/fredericseiler/trelabels/pull/17) of @Deutschi.

**Closed as completed by fredericseiler** 2019-05-09 14:35 UTC
